apiVersion: batch/v1
kind: Job
metadata:
  name: $JOB_NAME
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: run-notebook
        image: atspaeth/prpnb
        imagePullPolicy: Always
        envFrom:
            - configMapRef:
                name: $JOB_NAME-config
        volumeMounts:
          - mountPath: /root/.aws
            name: s3-credentials
        resources:
          requests:
            cpu: 1
            memory: "8Gi"
            nvidia.com/gpu: 0
          limits:
            cpu: 1
            memory: "16Gi"
            nvidia.com/gpu: 0
        command: ["/bin/bash", "-c"]
        args:
            - aws s3 cp "$(IN_URL)" notebook.ipynb &&
              jupyter nbconvert --ExecutePreprocessor.timeout=None
              --to notebook --allow-errors --inplace --debug
              --execute notebook.ipynb &&
              aws s3 cp notebook.ipynb "$(OUT_URL)" &&
              aws s3 rm "$(IN_URL)"
      restartPolicy: Never
      volumes:
        - name: s3-credentials
          secret:
            secretName: prpnb-s3-config
